version: '3.8'

services:
  app:
    build: ./backend/server
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb+srv://mireillemaherkhanna_db_user:<mireille>@cluster0.jmugj1z.mongodb.net/?appName=Cluster0
      - JWT_SECRET=K3f9sL!pQw8rZx1mT0vB
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  db-seed:
    build: ./backend/server
    command: npm run seed
    environment:
      - DB_URI=mongodb+srv://mireillemaherkhanna_db_user:<mireille>@cluster0.jmugj1z.mongodb.net/?appName=Cluster0
    depends_on:
      - mongo
    restart: "no" # Only run once on startup

volumes:
  mongo-data:
